/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTecnicosRouteImport } from './routes/_app.tecnicos'
import { Route as AppServiciosRouteImport } from './routes/_app.servicios'
import { Route as AppPagosRouteImport } from './routes/_app.pagos'
import { Route as AppMapaRouteImport } from './routes/_app.mapa'
import { Route as AppEvidenciasRouteImport } from './routes/_app.evidencias'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosRoute = AppTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => AppRoute,
} as any)
const AppServiciosRoute = AppServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => AppRoute,
} as any)
const AppPagosRoute = AppPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenciasRoute = AppEvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/empresas': typeof AppEmpresasRoute
  '/evidencias': typeof AppEvidenciasRoute
  '/mapa': typeof AppMapaRoute
  '/pagos': typeof AppPagosRoute
  '/servicios': typeof AppServiciosRoute
  '/tecnicos': typeof AppTecnicosRoute
}
export interface FileRoutesByTo {
  '/empresas': typeof AppEmpresasRoute
  '/evidencias': typeof AppEvidenciasRoute
  '/mapa': typeof AppMapaRoute
  '/pagos': typeof AppPagosRoute
  '/servicios': typeof AppServiciosRoute
  '/tecnicos': typeof AppTecnicosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/evidencias': typeof AppEvidenciasRoute
  '/_app/mapa': typeof AppMapaRoute
  '/_app/pagos': typeof AppPagosRoute
  '/_app/servicios': typeof AppServiciosRoute
  '/_app/tecnicos': typeof AppTecnicosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresas'
    | '/evidencias'
    | '/mapa'
    | '/pagos'
    | '/servicios'
    | '/tecnicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/empresas'
    | '/evidencias'
    | '/mapa'
    | '/pagos'
    | '/servicios'
    | '/tecnicos'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/empresas'
    | '/_app/evidencias'
    | '/_app/mapa'
    | '/_app/pagos'
    | '/_app/servicios'
    | '/_app/tecnicos'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos': {
      id: '/_app/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof AppTecnicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servicios': {
      id: '/_app/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof AppServiciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagos': {
      id: '/_app/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AppPagosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidencias': {
      id: '/_app/evidencias'
      path: '/evidencias'
      fullPath: '/evidencias'
      preLoaderRoute: typeof AppEvidenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppEvidenciasRoute: typeof AppEvidenciasRoute
  AppMapaRoute: typeof AppMapaRoute
  AppPagosRoute: typeof AppPagosRoute
  AppServiciosRoute: typeof AppServiciosRoute
  AppTecnicosRoute: typeof AppTecnicosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmpresasRoute: AppEmpresasRoute,
  AppEvidenciasRoute: AppEvidenciasRoute,
  AppMapaRoute: AppMapaRoute,
  AppPagosRoute: AppPagosRoute,
  AppServiciosRoute: AppServiciosRoute,
  AppTecnicosRoute: AppTecnicosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
