/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnicoRouteImport } from './routes/tecnico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTecnicosRouteImport } from './routes/_app.tecnicos'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'

const TecnicoRoute = TecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosRoute = AppTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/tecnico': typeof TecnicoRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/tecnicos': typeof AppTecnicosRoute
}
export interface FileRoutesByTo {
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/tecnico': typeof TecnicoRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/tecnicos': typeof AppTecnicosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/tecnico': typeof TecnicoRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/tecnicos': typeof AppTecnicosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresa'
    | '/login'
    | '/tecnico'
    | '/configuracion'
    | '/tecnicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/empresa' | '/login' | '/tecnico' | '/configuracion' | '/tecnicos' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/empresa'
    | '/login'
    | '/tecnico'
    | '/_app/configuracion'
    | '/_app/tecnicos'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  EmpresaRoute: typeof EmpresaRoute
  LoginRoute: typeof LoginRoute
  TecnicoRoute: typeof TecnicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnico': {
      id: '/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof TecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos': {
      id: '/_app/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof AppTecnicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppTecnicosRoute: typeof AppTecnicosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppTecnicosRoute: AppTecnicosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  EmpresaRoute: EmpresaRoute,
  LoginRoute: LoginRoute,
  TecnicoRoute: TecnicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
